server:
  servlet:
    context-path: /demo
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: d08cabf88383faa62a74
            client-secret: dc09531b10616110e6bfabb8e4f49a0bbaeae1f8
            redirect-uri-template: 'http://localhost:9000/login/oauth2/code/github'
